Question 1 - Write a Python program to select an item randomly from a list.

In [40]:
import random

list1=[1,2,3,4,5]
print(random.choice(list1))

3


Question 2 - Write a Python program to count the elements in a list until an element is a tuple.

In [47]:
list1=[66,34,45,99,(56,78),90,78]

count=0
for i in list1:
  if not isinstance(i,tuple):
    count=count+1
  else:
    break

print(count)

TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union

Question 3 - Create a dictionary of 5 countries with their currency details and display them.

In [45]:
dict1={
    'India':'Rupee',
    'China':'Yuan',
    'USA':'Dollar',
    'UK':'Pound',
    'Dubai':'Dirham'
    }
print(dict1)

{'India': 'Rupee', 'China': 'Yuan', 'USA': 'Dollar', 'UK': 'Pound', 'Dubai': 'Dirham'}


Question 4 - Write a Python program to reverse a tuple.

In [ ]:
tuple=(1, 2, 'Python', 'Java', 23.4, 77, 10)

print(tuple[::-1])

(10, 77, 23.4, 'Java', 'Python', 2, 1)


Question 5 - Create a Numpy array filled with all ones.

In [ ]:
import numpy as np

##1D
a1=np.ones(3,int)
print(a1)
print('-------------')
##2D
a2=np.ones([5,5],int)
print(a2)

[1 1 1]
-------------
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


Question 6 - Check whether a Numpy array contains a specified row.

In [ ]:
import numpy as np

arr=np.array(
            [[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15],
             [16,17,18,19,20]]
             )

print(arr)

print([11,12,13,14,15] in arr.tolist())
print([11,12,13,17,15] in arr.tolist())
print([1,2,3,4,5] in arr.tolist())
print([6,7,8,9,11] in arr.tolist())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
True
False
True
False


Question 7 - Compute mathematical operations on Array, Add & Multiply two matrices.

In [ ]:
import numpy as np
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3])
mat2 = ([3, 4, 6],[5, 6, 7],[6,56, 7])

##addition
res1=np.add(mat1,mat2)

##multiply
res2=np.dot(mat1,mat2)

print(res1)
print('-------------')
print(res2)

[[ 4 10 11]
 [ 8 10 15]
 [ 8 68 10]]
-------------
[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]


Question 8 - Find the most frequent value in a NumPy array.

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,1,1,1,1,2,2,2,2,7,7,7,7,7,7,7,7,7,7])

np.bincount(arr).argmax()

7

Question 9 - Flatten a 2d numpy array into ld array.

In [ ]:
import numpy as np

mat1 = np.array([[1, 6, 5],[3 ,4, 8],[2, 12, 3]])
res=mat1.flatten()
print(res)

[ 1  6  5  3  4  8  2 12  3]


Question 10 - Calculate the sum of all columns in a 2D NumPy array

In [ ]:
import numpy as np

mat1 = np.array([[1, 6, 5],[3 ,4, 8],[2, 12, 3]])
TwoDArray=mat1.tolist()
print(np.sum(TwoDArray,axis=0))

[ 6 22 16]


Question 11 - Calculate the average, variance and standard deviation in Python using NumPy 

In [ ]:
import numpy as np
import math
list1=[1,3,4,7,9,10]

print(np.mean(list1))
print(np.var(list1))
print(math.sqrt(np.var(list1)))

5.666666666666667
10.555555555555555
3.2489314482696545


Question 12 - Insert a space between characters of all the elements of a given NumPy array? 

In [ ]:
import numpy as np

arr = np.array(["hello", "hi", "how"],dtype=str)

res=np.char.join(" ",arr)
print(res)

['h e l l o' 'h i' 'h o w']


Question 13 - Sort the values in a matrix

In [ ]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1],[2,9,78],[98,67,100]])

print(np.sort(arr))

[[  2   3   4]
 [  0   1   5]
 [  2   9  78]
 [ 67  98 100]]
