Create a class for a bank and create methods to add clients and to perform transactions

Use pandas to convert column of data frame to series
Perform arithmetic operations on pandas series and check the elements of two series are same or not

In [7]:
import pandas as pd

# Sample DataFrame
data = {
    'A': [1, 2, 3, 4, 5],
    'B': [6, 7, 8, 9, 10]
}

df = pd.DataFrame(data)

# Convert a column of the DataFrame to a Series
series_A = df['A']
series_B = df['B']

# Perform arithmetic operations on pandas Series
sum_series = series_A + series_B
sub_series = series_A - series_B

# Check if elements of two Series are the same or not
elements_same = (series_A == series_B).all()

print("Series A:\n", series_A.values)
print("Series B:\n", series_B.values)
print("Sum of Series A and B:\n", sum_series.values)
print("Difference of Series A and B:\n", sub_series.values)
print("Are all elements of Series A and B same?", elements_same)  



Series A:
 [1 2 3 4 5]
Series B:
 [ 6  7  8  9 10]
Sum of Series A and B:
 [ 7  9 11 13 15]
Difference of Series A and B:
 [-5 -5 -5 -5 -5]
Are all elements of Series A and B same? False


decorator to count execution time of function 

In [13]:
import time

def runtime_decorator(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        print(f"Runtime of {func.__name__}: {end_time - start_time} seconds")
        return result
    return wrapper

# Example usage:
@runtime_decorator
def my_function():
    print("Hello Hi How are you")
    pass

my_function()

Hello Hi How are you
Runtime of my_function: 4.38690185546875e-05 seconds


Decimal to binary using recursion

In [3]:
def decimal_to_binary(decimal):
    if decimal == 0:
        return '0'  # Base case: Decimal 0 is binary 0
    elif decimal == 1:
        return '1'  # Base case: Decimal 1 is binary 1
    else:
        return decimal_to_binary(decimal // 2) + str(decimal % 2)

# Test the function
decimal_num = 12
binary_num = decimal_to_binary(decimal_num)
print(f"The binary representation of {decimal_num} is: {binary_num}")

The binary representation of 12 is: 1100


decorator to convert data type 

In [5]:
def convert_data_type(data_type):
    def decorator(func):
        def wrapper(*args, **kwargs):
            result = func(*args, **kwargs)
            try:
                return data_type(result)
            except (ValueError, TypeError):
                print(f"Error: Cannot convert {result} to {data_type.__name__}.")
                return None
        return wrapper
    return decorator

# Example usage:
@convert_data_type(float)
def divide(a, b):
    return a / b

@convert_data_type(int)
def concatenate(a, b):
    return str(a) + str(b)

# Test the decorated functions
result1 = divide(10, 2)
print("Result of divide function (converted to float):", result1)

result2 = concatenate(10, 20)
print("Result of concatenate function (converted to int):", result2)

result3 = divide(10, '2')
print("Result of divide function (error handling):", result3)


Result of divide function (converted to float): 5.0
Result of concatenate function (converted to int): 1020


TypeError: unsupported operand type(s) for /: 'int' and 'str'

reversed transpose of numpy 2D array

In [8]:
import numpy as np

# Create a sample 2D NumPy array
array_2d = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

# Transpose the array
transposed_array = np.transpose(array_2d)

# Reverse the order of rows in the transposed array
reversed_transpose_array = np.flip(transposed_array, axis=0)

print("Original array:")
print(array_2d)

print("\nReversed transpose of the array:")
print(reversed_transpose_array)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reversed transpose of the array:
[[3 6 9]
 [2 5 8]
 [1 4 7]]


fn to convert string to Palindrome

In [14]:
def make_palindrome(s):
    return s+s[::-1][1:]

# Test the function
string = input("Enter a string: ")
palindrome = make_palindrome(string)
print("Palindrome:", palindrome)


Palindrome: abcbabdbabcba


convert to decimal to bin, oct, hex

In [15]:
decimal_number = int(input("Enter a decimal number: "))

binary_number = bin(decimal_number)
octal_number = oct(decimal_number)
hexadecimal_number = hex(decimal_number)

print("Binary:", binary_number)
print("Octal:", octal_number)
print("Hexadecimal:", hexadecimal_number)


Binary: 0b101
Octal: 0o5
Hexadecimal: 0x5


Use decorators to log arguments of a function and return a value

In [17]:
def log_arguments(func):
    def wrapper(*args, **kwargs):
        print("Arguments:", args, kwargs)
        return func(*args, **kwargs)
    return wrapper

@log_arguments
def add(a, b):
    return a + b

result = add(3, 5)
print("Result:", result)


Arguments: (3, 5) {}
Result: 8


Sorting a list of tuples where each tuple has 2 elements and sorting the tuples based on second element

Ex. List1 = [('a', 2),('b',1)]
Sorted list = [('b', 1),('a',2)]

In [10]:
List1 = [('a', 2),('b',1)]
sorted_list=sorted(List1,key=lambda x:x[1])
print(sorted_list)

[('b', 1), ('a', 2)]
